### ISSUE TITLE
How to export onnx in fp64

### ISSUE THREAD

**Issue by RuiqingTang** [codename0og/hifi_testing_new#1]
I attempted to export my model to ONNX, and while the process was completed successfully, the inference results were unsatisfactory. I suspect this may be due to precision loss. I want to export the model with fp64 (double precision) to address this issue potentially. How can I export my model in fp64 precision?

**Comment by codename0og** [comment]
Sorry for late response. Been a while I used github ~
Now, fp64 won't resolve anything really in that particular case of yours + you can't just export it like that. You have to train an fp64 model which is not something an avg user can effectively do + barely any corpos involve fp64, it is a double precision and cosmic-scale requirements for memory
